# Generated by Django 3.1 on 2020-08-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('not done', 'not done')], max_length=50, null=True),
        ),
    ]
